### ISSUE TITLE
How inVisible route and remove path and markers 

### ISSUE THREAD

**Issue by sahaand** [amalChandran/trail-android#12]
hi thanks for your lib
how remove and invisible path and marker after draw

**Comment by amitnain4** [comment]
i also face same problem can u please provide us solution

**Comment by amalChandran** [comment]
The alpha branch has lot of bug fixes. Its now a simple view instead of a custom map fragment. Try it, you will be able to set it up in your project easily. @amitnain4 

 You can make the view invisible as of now. I will add a function to hide the route and markers explicitly.

**Comment by amitnain4** [comment]
Thanks @amalChandran  for your quick help .
but in alpha branch R.styleable.MapOverlayView ,R.styleable.MapOverlayView_routeStartMarkerImg 
messing . i check but there is no styles.xml file in this library . so request you to please resolve this .
thanks again

**Comment by amalChandran** [comment]
@amitnain4 The missing files are added. Please check now.

**Comment by amitnain4** [comment]
@amalChandran thanks buddy .
