### ISSUE TITLE
In Uber path is above text.

### ISSUE THREAD

**Issue by YasirAmeen** [amalChandran/trail-android#2]
Hey thank you fro great code, i want to know one thing. In uber poly line path is above the text, but using your code the path is showing below the code.

any hint??

**Comment by amalChandran** [comment]
Drawing a polyline over the text is way simpler as you can draw over the map without using polylines. For this you can get the route coordinates from map(latlng to screen co-ordinates api). One you have the points you can just draw lines using canvas. 

Its good to draw within the map as we dont want to hide the names of roads/highways.
