### ISSUE TITLE
Sometime It doesn't work

### ISSUE THREAD

**Issue by cinohub** [amalChandran/trail-android#3]
Thank for your supporting. Anyway, I got some issues, My app running perfect but Sometime I could not draw any line on the map. I don't know why my map was loaded done but the line did not appear.

Anyone who get the same error just hit the ideas below. 

Thank you!

**Comment by amalChandran** [comment]
@duongnv1996 Sorry about the delay. Now there is a better and smoother way to draw routes. Please have a look.
