### ISSUE TITLE
Several build issues

### ISSUE THREAD

**Issue by robertoestivill** [amalChandran/trail-android#6]
There are several issues that stop this repository from being built by only running `./gradlew installDebug`

1) `trails` module is missing `build.gradle`
Solution: add the missing `build.gradle` file

2) `./gradlew` is looking for the gradle wrapper jar which doesn't exists
Solution: add `gradle` folder with wrapper configuration

3) `local.properties` points to your development environment cause the command to fail as the sdk is not located in the given directory.
Solution: remove the `local.properties` file

Looking forward to test the sample
Cheers

**Comment by amalChandran** [comment]
@robertoestivill Thanks for pointing this out. I have pushed the  three changes you have suggested. Please have a look. There is so much scope for improvement.
