### ISSUE TITLE
Drawing goes wrong sometimes

### ISSUE THREAD

**Issue by ghost** [amalChandran/trail-android#8]
Hi,
Thanks for your great library. i was looking at demo and saw that the driving isn't correct on emulator. See below gif.
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/3052047/34916721-e03bd016-f951-11e7-8e35-3a17d57b8b03.gif)

**Comment by amalChandran** [comment]
Manafzar,

Please create a google map token from google api console and add it in the
project. Then it should work.

Thanks,
Amal

**Comment by ghost** [comment]
All right thanks i thought drawing maps is beside polyline API but it seems it's not.

**Comment by ghost** [comment]
Hello again,
I have added the google API key as you suggested but still the flickering is experienced as shown in below GIF:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3052047/35062863-af1dcd50-fbda-11e7-8cc5-4cde45d1a5cf.gif)

**Comment by ghost** [comment]
@amalChandran Can i ask what is the function to clear a drawn line? let's say i have drawn a path using setUpPath function and now i want to remove it from map. how can i do this? it should be pretty easy of course but i couldn't find the function for it

**Comment by danishsharma1993** [comment]
@manafzar have you solved this issue ? i am getting same.

**Comment by ghost** [comment]
@danishsharma1993 No sorry i couldn't find a solution either.

**Comment by cyberrob-zz** [comment]
using a real device might just solve the problem if you want quick fix.
